# Saint Seiya custom archetypes
!setname 0x1d7 Saint
!setname 0x1d8 Cloth
!setname 0x1ec Bronze Cloth
!setname 0x1d9 Bronze Saint
!setname 0x1da Silver Saint
!setname 0x1db Gold Saint
!setname 0x1dc Gold Cloth
!setname 0x1eb Silver Cloth
!setname 0x1dd Envoy of the Pope
!setname 0x1de Pope's Mandate
!setname 0x1df Ghost Saint
!setname 0x1e0 Steel Saint
!setname 0x1e1 Black Saint
!setname 0x1e2 Fragment of Sagittarius
!setname 0x1e3 God Warrior
!setname 0x1e4 Poseidon
!setname 0x1e5 Marine General
!setname 0x1e6 Pillar
!setname 0x1e7 Hades
!setname 0x1e8 Specter
!setname 0x1e9 Renegade Saint
!setname 0x1ea Meta

